config_rewrite: replace
langcode: en
status: true
dependencies:
  config:
    - core.entity_view_mode.media.thumbnail
    - field.field.media.image.field_media_in_library
    - field.field.media.image.image
    - image.style.thumbnail
    - media.type.image
  module:
    - image
id: media.image.thumbnail
targetEntityType: media
bundle: image
mode: thumbnail
content:
  image:
    type: image
    weight: 0
    label: hidden
    settings:
      image_style: thumbnail
      image_link: content
    third_party_settings: {  }
    region: content
hidden:
  created: true
  field_media_in_library: true
  langcode: true
  thumbnail: true
  uid: true
